# The name of the WandB project to use.
project: timotheboulet/EcoJAX

# The filters that will be applied to the config for accepting a run, following WandB filters.
filters:
  "summary_metrics._step":
    "$gte": 50000
  "config.benchmark_name": bench17_fp_hc

# How many samples maximal to use for the plot.
samples: 10000

# The minimum number of metrics to have in the run to be considered.
min_n_metrics: 10

# Which data types to log.
data_types:
  scalar : True
  histogram : False
  image_url: True
  config : True
  metadata : True

# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - override hydra/hydra_logging: default  
  - override hydra/job_logging: stdout 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .
  